### ISSUE TITLE
Fix broken link to image

### ISSUE THREAD

**Issue by gdedi001** [Lyn-01/prj-rev-bwfs-dasmoto#3]
The following location is incorrect
https://github.com/Lyn-01/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L10

Try this instead
`url(/Dasmoto/resources/images/pattern.jpeg`

**Comment by Lyn-01** [comment]
If I use the suggested url, the image does not appear. Is there something I am doing wrong?

**Comment by gdedi001** [comment]
did you upload the new code to your github? I'd like to take a look.

**Comment by Lyn-01** [comment]
Yes, I have changed the code directly in Github, you should be able to see it.

**Comment by gdedi001** [comment]
It's working for me. Try using a text editor called brackets. When you open the editor, navigate to the top right and click on the lightning bolt icon. This will create a realtime connection to your browser allowing you to see the results of your code automatically.
http://brackets.io

**Comment by Lyn-01** [comment]
Unfortunately also in brackets the image still isn't visible. I tried a few other changes in layout and they do appear immediately as you said. 
Can the image problem have something to do with the path that the page is saved on? On my computer the files are stored in the folder, but the url on github refers to: prj-rev-bwfs-dasmoto.blob.master.

**Comment by Lyn-01** [comment]
I am having the same problem in the broadway project, do you see the background image in the top of the webpage?

**Comment by Lyn-01** [comment]
I found the answer on slack: it works! 
background-image: url("../images/pattern.jpeg");
